version: 2.1

executors:
  node:
    docker:
      - image: cimg/node:14.17.6
    working_directory: ~/app
  docker_builder:
    docker:
      - image: circleci/buildpack-deps:bionic
        user: root
jobs:
  build:
    parameters:
      NUXT_APP_NODE_URL:
        type: string
      NUXT_APP_NODE_WS:
        type: string
      NUXT_APP_NETWORK_NAME:
        type: string
    executor: node
    steps:
      - checkout
      - run:
          name: Install
          command: npm install
      - run:
          name: Generate
          command: NUXT_APP_NODE_URL="<< parameters.NUXT_APP_NODE_URL >>" NUXT_APP_NODE_WS="<< parameters.NUXT_APP_NODE_WS >>" NUXT_APP_NETWORK_NAME="<< parameters.NUXT_APP_NETWORK_NAME >>" npm run generate
      - persist_to_workspace:
          root: .
          paths:
            - .
          
  docker_push_tag:
    executor: docker_builder
    environment:
      DOCKERHUB_REPO: aeternity/aeternal-frontend
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - attach_workspace:
          at: .
      - run:
          name: Build and push Docker image to DockerHub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t ${DOCKERHUB_REPO:?} -t ${DOCKERHUB_REPO:?}:latest -f nginx.Dockerfile .
            docker push ${DOCKERHUB_REPO:?}
            docker push ${DOCKERHUB_REPO:?}:latest

workflows:
  version: 2
  build_push:
    jobs:
      - build:
          NUXT_APP_NODE_URL: "https://mainnet.aeternity.io/mdw"
          NUXT_APP_NODE_WS: "wss://mainnet.aeternity.io/mdw/websocket"
          NUXT_APP_NETWORK_NAME: "MAIN NET"
          filters:
            tags:
              only: /^v.*$/
      - docker_push_tag:
          context: ae-dockerhub
          requires:
            - build
