name: Production Testnet Pipeline

on:
  push:
    branches:
      - master
  release:
    types: [created]

env:
  ENV: "prd"
  APP: "mdw-frontend-testnet"

jobs:
  main:
    runs-on: ubuntu-latest
    name: Testnet Production Pipeline
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - uses: GoogleCloudPlatform/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: ""
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"ci","section":"CI / CD","hidden":false},{"type":"test","section":"Testing","hidden":false},{"type":"refactor","section":"Refactorings","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false}]'

      - name: Set up Docker Buildx
        id: buildx
        # Use the action from the master, as we've seen some inconsistencies with @v1
        # Issue: https://github.com/docker/build-push-action/issues/286
        uses: docker/setup-buildx-action@master
        with:
          install: true

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          # Key is named differently to avoid collision
          key: ${{ runner.os }}-${{ env.ENV }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ env.ENV }}-buildx

      - name: Log in to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Extract metadata for docker
        if: |
          github.event_name == 'push' ||
          startsWith(github.ref, 'refs/tags/v')
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: aeternity/mdw-frontend:testnet
          tags: |
            type=raw,value=latest,enable=${{ endsWith(GitHub.ref, 'main') }}
            type=raw,value=${{ steps.release.outputs.tag_name }},enable=${{ endsWith(GitHub.ref, 'main') }}
            type=ref,event=tag
            type=ref,event=pr

      - name: Build and push docker image
        if: |
          github.event_name == 'push' ||
          startsWith(github.ref, 'refs/tags/v')
        uses: docker/build-push-action@v2
        with:
          context: .
          file: nginx.Dockerfile
          build-args: |
            NUXT_APP_NETWORK_NAME: "TESTNET v0.7.1" 
            NUXT_APP_NODE_URL: "https://testnet.aeternity.io/v3" 
            NUXT_APP_MDW_URL: "https://testnet.aeternity.io/mdw" 
            NUXT_APP_NODE_WS: "wss://testnet.aeternity.io/mdw/websocket"  
            NUXT_APP_OTHER_DEPLOYMENTS: "MAINNET@https://explorer.aeternity.io" 
            NUXT_APP_ENABLE_FAUCET: "true"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          # Note the mode=max here
          # More: https://github.com/moby/buildkit#--export-cache-options
          # And: https://github.com/docker/buildx#--cache-tonametypetypekeyvalue
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

      - name: Move cache
        if: github.event_name == 'pull_request' && github.event.action == 'opened' || github.event.action == 'synchronize'
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - uses: actions/checkout@v2
        with:
          repository: aeternity/gitops-apps.git
          ref: prd
          persist-credentials: false
          fetch-depth: 0

      - name: Production Deploy
        if: ${{ steps.release.outputs.release_created }}
        uses: aeternity/ae-github-actions/argocd-deploy@v4
        with:
          url-prefix: ${{ steps.release.outputs.tag_name }}
          env: ${{ env.ENV }}
          app: ${{ env.APP }}

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          repository: aeternity/gitops-apps
          github_token: ${{ secrets.BOT_GITHUB_TOKEN }}
          branch: prd
